


/*      BOUZRI MOHAMED,AYOUB FADOUACHE, ASMAE HAYAR 2APG3M       */



var catalogue = [ 
    {   code : 1,
        vrai : true,
        nom : "Lenovo",
        desc: "Ideapad 100-15IBD -15.6 Led HD Intel Core i5 - Ram 4Go - 500Go - Windows 10",
        prix: 4979,
		image : "../images/img1.jpg"
    },
    {   code : 2,
        vrai : false,
        nom : "Lenovo",
        desc: "IDEAPAD 330-15IGM CELERON N4000 15,6 (1To, 4Go) Noir Onyx",
        prix: 2699,
		image : "../images/img2.jpg"
    },
    {   code : 3,
        vrai : true,
        nom  : "Lenovo" , 
        desc : "PC PORTABLE IdeaPad 330 15IGM-N4000 4GO 1TO 15.6' FreeDos BLACK" , 
        prix :2790,
		image : "../images/img3.jpg"
    },
    {   code : 4,
        nom: "Lenovo",
        desc: "S340-15IML 15,6' LED IPS , i5-10210U, 8GB, 512GB, GEFORCE MX250",
        prix: 8395,
		image : "../images/img4.jpg"
    },
    {   code : 5,
        vrai : false,
        nom: "Lenovo",
        desc: "PC Portable IP330 AMD A4-9125 4Go 1To 15,6 (couleur: Blanc)",
        prix: 2790,
        image : "../images/img5.jpg"
    },
    {   code : 6,
        vrai : false,
        nom: "Lenovo",
        desc: "Yoga Chrome C630 81JX001TGE i5-8250U 8GB / 128GB SSD 15 FHD ChromeOS",
        prix: 6700,
        image : "../images/img6.jpg"
    },
    {   code : 7,
        vrai : false,
        nom: "Lenovo",
        desc: "IDEAPAD S340-14IIL 14  ULTRABOOK Core i5 (10th) 8GB/ 512 SSD/ Win10",
        prix: 8200,
        image : "../images/img7.jpg"
    },
    {   code : 8,
        vrai : false,
        nom: "Lenovo",
        desc: "Lenovo Lenovo V130 i5-7020U 4GB.1000GB. 15.6 /Intel HD Graphics",
        prix: 5499,
        image : "../images/img8.jpg"
    },
    {   code : 9,
        vrai : true,
        nom: "HP",
        desc: "PC Portable Probook 640 G1 Core i3 4eme 320Gb 8 GB RAM 14 remis a neuf",
        prix: 2699,
        image : "../images/img9.jpg"
    },
    {   code : 10,
        vrai : false,
        nom: "HP",
        desc: "Hp Elitebook X360 1030 G4-13,3- i5 8365u- RAM 8GB-512SSD-Win10 Pro-Azerty-Argent",
        prix: 14800,
        image : "../images/img10.jpg"
    },
    {   code : 11,
        vrai : false,
        nom: "HP",
        desc: "Hp Elitebook 850 G5 -15 Full HD- i5 8250u- 256G SSD- RAM8GB- Win 10 Pro- Argent",
        prix: 10200,
        image : "../images/img11.jpg"
    },
    {   code : 12,
        vrai : false,
        nom: "HP",
        desc: "Hp PC Portable Probook 640 G1 Core i3 4th Gén 320GB - 4GB RAM 14 -Remis a Neuf",
        prix: 2374,
        image : "../images/img12.jpg"
    },
    {   code : 13,
        vrai : false,
        nom: "HP",
        desc: "Hp PC PORTABLE 450 G7 i7-10510U 15.6 8GB 1TB FreeDos 1Yr silver",
        prix: 9990,
        image : "../images/img13.jpg"
    },
    {   code : 14,
        vrai : true,
        nom: "HP",
        desc: "Hp Probook 430 G6- 13.3- i5 8265u- 256GB- RAM8GB- Win10 Pro- Azerty- Argent ",
        prix: 8100,
        image : "../images/img14.jpg"
    },
    {   code : 15,
        vrai : false,
        nom: "HP",
        desc: "Hp Station de travail mobile ZBook 15 G4 15.6 Core i7 7700HQ 8 Go RAM 256Ssd",
        prix: 12000,
        image : "../images/img15.jpg"
    },
    {   code : 16,
        vrai : true,
        nom: "DELL",
        desc: "DELL PC Portable Latitude E7250 - i5-5300U - 8GB /128 Go SSD BON OCCASION",
        prix: 3150,
        image : "../images/img16.jpg"
    },
    {   code : 17,
        vrai : false,
        nom: "DELL",
        desc: "DELL PC PORTABLE LATITUDE E7240 I5 4éme 8G/128SSD BONNE OCCASION",
        prix: 2650,
        image : "../images/img17.jpg"
    },
    {   code : 18,
        vrai : false,
        nom: "DELL",
        desc: "DELL Latitude 5591-15,6-Core I5-8400H-RAM 8GB-256 SSD-Windows 10 Pro",
        prix: 10900,
        image : "../images/img18.jpg"
    },
    {   code : 19,
        vrai : true,
        nom: "DELL",
        desc: "DELL Latitude 7480 i5-6300U 2.40Ghz 8Go 256Go SSD Intel HD Graphics 520 Neuf",
        prix: 6800,
        image : "../images/img19.jpg"
    },
    {   code : 20,
        vrai : false,
        nom: "DELL",
        desc: "DELL Latitude 5500-15,6-Core i5-8365U -RAM 8GB-256 SSD-Windows 10 Pro",
        prix: 9900,
        image : "../images/img20.jpg"
    }
    
 ];
  
  var catalogueTVs = [ 
    {   code : 21,
        vrai : false,
        nom : "visio",
        desc: "Visio TV 43' Full HD - Récepteur integré + TNT + HDMI + USB - Garnatie 1 AN",
        prix: 2259,
        image : "../images/img21.jpg"
    },
    {   code : 22,
        vrai : false,
        nom : "Hisense",
        desc: "Hisense 43″ FHD SMART TV 43B6200PW + IP TV 1 AN + Récepteur intégré - Noir.",
        prix: 2899,
        image : "../images/img22.jpg"
    },
    {   code : 23,
        vrai : false,
        nom  : "Samsung" , 
        desc : "Samsung Smart TV 50 TU7000 Crystal UHD 4K série 7 HDR 10+ Récepteur Intégré Bluetooth TNT Modèle 2020" , 
        prix : 5098,
        image : "../images/img23.jpg"
    },
    {   code : 24,
        vrai : false,
        nom: "Hisense",
        desc: "Hisense 32″ FHD SMART TV 32B6200HW avec 1 AN IP-TV + Récepteur intégré - Noir",
        prix: 1699,
        image : "../images/img24.jpg"
    },
    {   code : 25,
        vrai : true,
        nom: "Leader",
        desc: "Leader 24' LE-CTV2400 LED TV - Noir",
        prix: 849,
        image : "../images/img25.jpg"
    },
    {   code : 26,
        vrai : true,
        nom: "Visio",
        desc: "Visio TV LED 32″ HD 720p Framless Design Recepteur integré - Garantie 1 an",
        prix: 1209,
        image : "../images/img26.jpg"
    },
    {   code : 27,
        vrai : true,
        nom: "Visio",
        desc: "Visio TV LED 24″ FULL HD Récepteur intégré + TNT + Moniteur - garantie 1 an",
        prix: 969,
        image : "../images/img27.jpg"
    },
    {   code : 28,
        vrai : false,
        nom: "Hisense",
        desc: "Hisense 32″ FHD SMART TV 32B6200HW avec Récepteur intégré - Noir.",
        prix: 1599,
        image : "../images/img28.jpg"
    },
    {   code : 29,
        vrai : true,
        nom: "Samsung",
        desc: "Samsung 32″ HD UA32N5003AKXMV - LED TV – Noir",
        prix: 1399,
        image : "../images/img29.jpg"
    },
    {   code : 30,
        vrai : false,
        nom: "Revolution",
        desc: "Revolution TV LED 55' Smart Android 9.0 Frameless Design UHD 4K + Récepteur integré / TNT",
        prix: 4279,
        image : "../images/img30.jpg"
    },
    {   code : 31,
        vrai : false,
        nom: "Samsung",
        desc: "Samsung 43' LED Full HD Smart TV - 43N5300 - Noir",
        prix: 3049,
        image : "../images/img31.jpg"
    },
    {   code : 32,
        vrai : false,
        nom: "Samsung",
        desc: "Samsung 75' 4K UHD QLED Smart TV - 75Q60 - Noir",
        prix: 39990,
        image : "../images/img32.jpg"
    },
    {   code : 33,
        vrai : false,
        nom: "Visio",
        desc: "Visio TV 43' Smart Full HD Android 8.0 avec Récepteur intégré + TNT",
        prix: 2599,
        image : "../images/img33.jpg"
    },
    {   code : 34,
        vrai : false,
        nom: "Samsung",
        desc: "Samsung 49' LED Full HD Smart TV - 49N5300 - Noir",
        prix: 3599,
        image : "../images/img34.jpg"
    },
    {   code : 35,
        vrai : false,
        nom: "Samsung",
        desc: "Samsung TV 32' LED HD - Satellite intégré-HDMI-TNT-USB - 32N5000 + Support Mural - Garantie 1 ANS",
        prix: 1599,
        image : "../images/img35.jpg"
    },
    {   code : 36,
        vrai : false,
        nom: "LG",
        desc: "LG 55' Ultra HD 4K 55UK6470PLC Smart LED TV - Noir",
        prix: 9719,
        image : "../images/img36.jpg"
    },
    {   code : 37,
        vrai : false,
        nom: "LG ",
        desc: "LG TV Led lg 49um7310 4k smart wifi récepteur intégrée 2019",
        prix: 4650,
        image : "../images/img37.jpg"
    },
    {   code : 38,
        vrai : false,
        nom: "LG UHD",
        desc: "LG TV UHD 43'' UM7340 Smart IPS 4K Ecran 4K Active HDR avec ThinQ AI / Télécommande Magique",
        prix: 4099,
        image : "../images/img38.jpg"
    },
    {   code : 39,
        vrai : false,
        nom: "LG",
        desc: "LG TV LED 43LM5500PVA NUM NEW",
        prix: 3190,
        image : "../images/img39.jpg"
    },
    {   code : 40,
        vrai : false,
        nom: "LG",
        desc: "LG TV LED 55SM9000 SMART TV 4K",
        prix: 11880,
        image : "../images/img40.jpg"
    }
    ];

var cataloguePhones = [ 
    {   code : 41,
        vrai : true,
        nom : "Huawei Y5P",
        desc: "Huawei Y5P 5.45' (2Go, 32Go) 8MP/5MP Android - Vert",
        prix: 899,
        image : "../images/img41.jpg"
    },
    {   code : 42,
        vrai : false,
        nom : "Realme 5",
        desc: "Realme 5(128Go,4Go)-5000mAh-Al Quad Camera-Snapdragon 665 AIE-Violet",
        prix: 1999,
        image : "../images/img42.jpg"
    },
    {   code : 43,
        vrai : false,
        nom  : "XIAOMI Redmi Note 9S" , 
        desc : "XIAOMI Redmi Note 9S 6.67' (4Go, 64Go) 48MP+8MP+5MP+2MP/16MP Android - Gris" , 
        prix : 2550,
        image : "../images/img43.jpg"
    },
    {   code : 44,
        vrai : true,
        nom: "Samsung Galaxy A015F",
        desc: "Samsung Galaxy A015F 5.7' (16Go, 2Go) Dual SIM Android 13MP+2MP/5MP - Noir",
        prix: 1099,
        image : "../images/img44.jpg"
    },
    {   code : 45,
        vrai : false,
        nom: "Samsung Galaxy A30s",
        desc: "Samsung Galaxy A30s 6.4' (128Go, 4Go) Android 25MP+8MP+5MP/16MP - Noir",
        prix: 2178,
        image : "../images/img45.jpg"
    },
    {   code : 46,
        vrai : true,
        nom: "Samsung Galaxy A71",
        desc: "Samsung Galaxy A71 6.7' (128Go, 6Go) Android 64MP+12MP+5MP+5MP/32MP - Argent",
        prix: 4189,
        image : "../images/img46.jpg"
    },
    {   code : 47,
        vrai : false,
        nom: "Samsung Galaxy S10",
        desc: "Samsung Galaxy S10, 6.1', 8Go, 128Go - BLEU",
        prix: 6490,
        image : "../images/img47.jpg"
    },
    {   code : 48,
        vrai : true,
        nom: "Samsung Galaxy A11",
        desc: "Samsung Galaxy A11 6.4' (2Go, 32Go) 13MP+5MP+2MP/8MP Android - Noir",
        prix: 1479,
        image : "../images/img48.jpg"
    },
    {   code : 49,
        vrai : true,
        nom: "Samsung Galaxy A20s",
        desc: "Samsung Galaxy A20s 6.5' 4G (3Go, 32Go) Android - Noir - 1 an de garantie",
        prix: 1399,
        image : "../images/img49.jpg"
    },
    {   code : 50,
        vrai : false,
        nom: "Samsung Galaxy A51",
        desc: "Samsung Galaxy A51 - 6.5' FHD+ - (6GB - 128GB) - Android10.0 - 4G - Camera 48MP-Blanc",
        prix: 2968,
        image : "../images/img50.jpg"
    },
    {   code : 51,
        vrai : true,
        nom: "XIAOMI Redmi Note 8",
        desc: "XIAOMI Redmi Note 8 4G 6.3' (4Go, 64Go) Android - Bleu",
        prix: 1899,
        image : "../images/img51.jpg"
    },
    {   code : 52,
        vrai : true,
        nom: "XIAOMI Redmi Note 8",
        desc: "XIAOMI Redmi Note 8 4G 6.3' (4Go, 64Go) Android - Noir",
        prix: 1899,
        image : "../images/img52.jpg"
    },
    {   code : 53,
        vrai : true,
        nom: "Huawei Y7P",
        desc: "Huawei Y7P 6.39' 4G (4Go, 64Go) Android 48MP+8MP+2MP/8MP - Noir",
        prix: 1690,
        image : "../images/img53.jpg"
    },
    {   code : 54,
        vrai : false,
        nom: "XIAOMI Redmi Note 8",
        desc: "XIAOMI Redmi Note 8 4G 6.3' (4Go, 64Go) Android - Blanc",
        prix: 1899,
        image : "../images/img54.jpg"
    },
    {   code : 55,
        vrai : false,
        nom: "Samsung S10 Lite",
        desc: "Samsung S10 Lite 6.7' (128Go, 8Go) 48MP+12MP+5MP/32MP Android - Bleu - 1 an de garantie",
        prix: 5790,
        image : "../images/img55.jpg"
    },
    {   code : 56,
        vrai : true,
        nom: "Realme 5",
        desc: "Realme 5(128Go, 4Go)-5000mAh-Al Quad Camera-Snapdragon 665-Bleu",
        prix: 1999,
        image : "../images/img56.jpg"
    },
    {   code : 57,
        vrai : true,
        nom: "Samsung Galaxy A10s",
        desc: "Samsung Galaxy A10s, 6.2', 2Go, 32Go - Noir - Garantie 1 an",
        prix: 1347,
        image : "../images/img57.jpg"
    },
    {   code : 58,
        vrai : true,
        nom: "Samsung Galaxy A015F",
        desc: "Samsung Galaxy A015F 5.7' (16Go, 2Go) Dual SIM Android 13MP+2MP/5MP - Rouge",
        prix: 1099,
        image : "../images/img58.jpg"
    },
    {   code : 59,
        vrai : false,
        nom: "Realme C3",
        desc: "Realme C3(64Go,3Go)- 5000mAh - 12Mp Triple Caméra - 6.52' Fullscreen-G70- Rouge",
        prix: 1549,
        image : "../images/img59.jpg"
    },
    {   code : 40,
        vrai : false,
        nom: "Realme 6",
        desc: "Realme 6 (128Go, 8Go) 64MP Caméra 90Hz Affichage 30W Charge Flash G90T-Bleu",
        prix: 2899,
        image : "../images/img60.jpg"
    }
    ];